name: gasra_monitoring
description: A new Flutter project

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.1
  provider: ^6.1.2
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  image_picker: ^1.0.7
  photo_view: ^0.14.0
  simple_animations: ^5.0.2
  firebase_core: ^2.17.0
  firebase_messaging: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/ban.jpeg
    - assets/images/ban_head_20.png
    - assets/images/ban_head_40.png
    - assets/images/ban_chassis_20.png
    - assets/images/ban_chassis_40.png
    - assets/images/auth_background.png
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_cng.png"
  min_sdk_android: 21
